[package]
name = "ink-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
validator = { package = "ink-validator-core", path = ".." }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4.3"
